package com.aerospike.generator.annotations;

import java.lang.annotation.ElementType;
import java.lang.annotation.Retention;
import java.lang.annotation.RetentionPolicy;
import java.lang.annotation.Target;

/**
 * Intelligently generates test data based on field names and types.
 * 
 * <p>This annotation can be applied at the class level to enable automatic,
 * intelligent test data generation for all fields in the class. The generator
 * analyzes field names and types to determine the most appropriate data generator.</p>
 * 
 * <h3>How It Works</h3>
 * <p>The {@code GenMagicProcessor} analyzes field names to provide contextually
 * appropriate data. For example:</p>
 * <ul>
 *   <li>Fields named "email" or "emailAddress" → generates email addresses</li>
 *   <li>Fields named "firstName" or "lastName" → generates person names</li>
 *   <li>Fields named "price" or "cost" → generates currency-formatted numbers</li>
 *   <li>Fields named "birthday" or "dateOfBirth" → generates past dates</li>
 *   <li>Fields named "isActive" or "isVerified" → generates booleans with appropriate ratios</li>
 *   <li>And many more patterns...</li>
 * </ul>
 * 
 * <h3>Usage Examples</h3>
 * <pre>{@code
 * @GenMagic
 * public class User {
 *     private String firstName;      // Auto-generates first name
 *     private String lastName;       // Auto-generates last name
 *     private String email;           // Auto-generates email
 *     private Date dateOfBirth;       // Auto-generates past date
 *     private boolean isActive;       // Auto-generates boolean (mostly true)
 *     private Integer age;            // Auto-generates age (1-100)
 *     
 *     @GenExclude
 *     private String password;        // Excluded from generation
 * }
 * }</pre>
 * 
 * <p><b>Priority:</b> Field-level annotations (e.g., {@code @GenString},
 * {@code @GenNumber}) take precedence over {@code @GenMagic}. Fields with
 * {@code @GenExclude} are skipped.</p>
 * 
 * <p><b>Plural Support:</b> The processor supports plural field names (e.g.,
 * "emails", "addresses", "zipCodes") and automatically matches them to appropriate
 * generators.</p>
 * 
 * <p>See {@link GenMagicProcessor} for a complete list of supported patterns.</p>
 */
@Retention(RetentionPolicy.RUNTIME)
@Target({ElementType.TYPE})
public @interface GenMagic {
    /**
     * Percentage chance (0-100) that generated values will be null.
     * 
     * <p>This applies to all fields generated by GenMagic. Individual fields
     * can still be null based on their specific generator logic.</p>
     * 
     * @return The null percentage (0-100), default is 0 (never null)
     */
    int percentNull() default 0;
}
